---
title: "JTPA"
author: "Achim Ahrens"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library("ddml")
library("haven")
library("estimatr")
library("dplyr")
library("texreg")

# load data
dta <- read_dta("http://fmwww.bc.edu/repec/bocode/j/jtpa.dta")
dta <- as.data.frame(dta)
dta$prevearn_sq <- dta$prevearn^2

# define control variables
controls <- c("hsorged","black","hispanic","married","wkless13","class_tr",
              "ojt_jsa","age2225","age2629","age3035","age3644","age4554","f2sms",
              "prevearn","prevearn_sq","sex")

# define variable objects
y <- dta$earnings
D <- dta$training
Z <- dta$assignmt
X <- model.matrix(~sex*(.),data=dta[,controls])[,-1]

# define estimation formulas
ols_fm <- as.formula(paste("earnings~training+",paste(controls,collapse="+")))
iv_fm <- as.formula(paste("y~D+",paste(colnames(X),collapse="+"),
                          "|Z+",paste(colnames(X),collapse="+")))
```

## OLS and TSLS estimates

For reference, we estimate the OLS and TSLS coefficients with and without control variables.

```{r cars}
# estimation
lm1<-lm_robust(earnings~training,data=dta)
lm2<-lm_robust(ols_fm,data=dta)  
iv1<-iv_robust(y~D|Z,data=data.frame(y,D,Z,X))
iv2<-iv_robust(iv_fm,data=data.frame(y,D,Z,X))
screenreg(list(lm1,lm2,iv1,iv2),
          include.ci=FALSE,
          custom.coef.map=list("training"="Training",
                               "D"="Training"),
          custom.gof.rows = list("Controls"=c("No","Yes","No","Yes")) 
          )
```
## DML with lasso


```{r pressure, echo=FALSE}
plm_lasso <- ddml_plm(y,Z,X,
                       sample_folds=5,
                       learners=list(what=mdl_glmnet))
late_lasso <- ddml_late(y,D,Z,X,
                        sample_folds=5,
                        learners=list(what=mdl_glmnet))
pliv_lasso <- ddml_pliv(y,D,Z,X,
                        sample_folds=5,
                        learners=list(what=mdl_glmnet))
 
# create texreg-compatible object from `late_lasso`
late_lassoTex <- createTexreg(coef.names="training",
                              coef=summary(late_lasso)[1],
                              se=summary(late_lasso)[2],
                              pvalues=summary(late_lasso)[4]
                              )

screenreg(list(plm_lasso$ols_fit,
               pliv_lasso$iv_fit,
               late_lassoTex),
          custom.coef.map=list("D_r"="training",
                               "training"="training" 
                               ),
          custom.gof.rows=list("Estimator"=c("DML-PLM",
                                              "DML-PLIV",
                                              "DML-LATE"))
          )
```

## DML with multiple learners

```{r}
learners_multiple <- list(list(fun = ols),
                          list(fun = mdl_glmnet),
                          list(fun = mdl_glmnet,
                               args = list(alpha = 0)),
                          list(fun = mdl_xgboost,   
                               args = list(nrounds = 800,
                                         max_depth=1,
                                         early_stopping_rounds=10)),
                          list(fun = mdl_xgboost,   
                               args = list(nrounds = 800,
                                         max_depth=2,
                                         early_stopping_rounds=10)),
                          list(fun = mdl_xgboost, 
                               args = list(nrounds = 800,
                                         max_depth=4,
                                         early_stopping_rounds=10))
                                          )

plm_multi <- ddml_plm(y,Z,X,
                       learners=learners_multiple,
                       ensemble_type = "nnls",
                       custom_ensemble_weights = diag(length(learners_multiple)),
                       shortstack = TRUE,
                       sample_folds=5
                       )
late_multi <- ddml_late(y,D,Z,X,
                       learners=learners_multiple,
                       ensemble_type = "nnls",
                       custom_ensemble_weights = diag(length(learners_multiple)),
                       shortstack = TRUE,
                       sample_folds=5
                       )
pliv_multi <- ddml_pliv(y,D,Z,X,
                         learners=learners_multiple,
                         ensemble_type = "nnls",
                         custom_ensemble_weights = diag(length(learners_multiple)),
                         shortstack = TRUE,
                         sample_folds=5
                         )

# create texreg-compatible object from `late_lasso`
late_multi_lassoTex <- createTexreg(coef.names="training",
                              coef=summary(late_multi)[1,1],
                              se=summary(late_multi)[1,2],
                              pvalues=summary(late_multi)[1,4]
                              )

screenreg(list(plm_multi$ols_fit[[1]],
               pliv_multi$iv_fit[[1]],
               late_multi_lassoTex),
          custom.coef.map=list("D_r"="training",
                               "training"="training" 
                               ),
          custom.gof.rows=list("Estimator"=c( "DML-PLM",
                                              "DML-PLIV",
                                              "DML-LATE"))
          )

lapply(late_multi$weights,function(x) x[,1,drop=FALSE])
```