#!/usr/bin/env python3
"""Run `gn_ddml package.do` in Stata's batch mode and turn its log into
`_GN/Stata/GN_ddml_package_output.txt` with `# @snippet:NAME ... # @end`
blocks.

The .do file wraps each block of interest with
    display "###BEGIN_OUT:NAME###"
    <command>
    display "###END_OUT:NAME###"
so that we can slice the log file by simple text matching.
"""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


HERE        = Path(__file__).resolve().parent
STATA_DIR   = HERE / "Stata"
DO_FILE     = STATA_DIR / "gn_ddml_package.do"
LOG_FILE    = STATA_DIR / "gn_ddml_package.log"
OUTPUT_FILE = STATA_DIR / "GN_ddml_package_output.txt"

DEFAULT_STATA = "/Applications/StataNow/StataSE.app/Contents/MacOS/stata-se"
STATA_BIN     = os.environ.get("STATA_BIN", DEFAULT_STATA)

SECTION_ORDER = ["ols_out", "dml_out", "ssw_out",
                 "rbl_est_out", "final_out", "fsw_out"]

BEGIN = re.compile(r"###BEGIN_OUT:(\w+)###")
END   = re.compile(r"###END_OUT:(\w+)###")
# Stata log line conventions:
#   ". command"      — echoed input
#   "> continuation" — wrapped echoed input
# These are noise in the output tab, since the Code tab already shows the
# command. Strip them so the captured output is just the result table.
ECHO_LINE = re.compile(r"^[\.>](?:\s|$)")


def run_stata() -> None:
    if not Path(STATA_BIN).is_file():
        sys.exit(f"Stata binary not found at {STATA_BIN}. "
                 "Set STATA_BIN in the environment to override.")
    # Stata -b writes its log into the cwd, so cd into the Stata dir.
    cmd = [STATA_BIN, "-b", "do", DO_FILE.name]
    print(f"[run_stata] running: {' '.join(cmd)} (cwd={STATA_DIR})")
    result = subprocess.run(cmd, cwd=STATA_DIR)
    if result.returncode != 0:
        sys.exit(f"Stata exited with status {result.returncode}.")
    if not LOG_FILE.exists():
        sys.exit(f"Stata produced no log at {LOG_FILE}.")


def slice_log(log_text: str) -> dict[str, str]:
    """Return {snippet_name: captured_text} from the log between BEGIN/END markers."""
    out: dict[str, list[str]] = {}
    current: str | None = None
    buf: list[str] = []
    for raw in log_text.splitlines():
        # Skip the command echo lines that contain literal `display "###..."`.
        if 'display "###' in raw:
            continue
        m_b = BEGIN.search(raw)
        if m_b:
            current = m_b.group(1)
            buf = []
            continue
        m_e = END.search(raw)
        if m_e:
            if current == m_e.group(1):
                out[current] = "\n".join(buf).strip("\n")
                current = None
                buf = []
            continue
        if current is not None:
            # Strip Stata command echo / wrap-continuation lines.
            if ECHO_LINE.match(raw):
                continue
            buf.append(raw)
    # Final sanity check
    missing = [n for n in SECTION_ORDER if n not in out]
    if missing:
        print(f"[run_stata] WARNING: log missing sections {missing}", file=sys.stderr)
    return out


def write_output_file(slices: dict[str, str]) -> None:
    lines: list[str] = [
        "# Outputs produced by `gn_ddml package.do` (auto-generated by run_stata.py).",
        "# DO NOT edit by hand — re-run `make stata-run` to regenerate.",
        "",
        "",
    ]
    for name in SECTION_ORDER:
        if name not in slices:
            continue
        lines.append(f"# @snippet:{name}")
        lines.append(slices[name].rstrip())
        lines.append("# @end")
        lines.append("")
        lines.append("")
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"[run_stata] wrote {OUTPUT_FILE.relative_to(HERE.parent)} "
          f"with {sum(1 for n in SECTION_ORDER if n in slices)} snippets")


def main() -> int:
    run_stata()
    slices = slice_log(LOG_FILE.read_text(errors="replace"))
    write_output_file(slices)
    return 0


if __name__ == "__main__":
    sys.exit(main())
